### ISSUE TITLE
Issue when building 

### ISSUE THREAD

**Issue by Yasha-ops** [egemenertugrul/wolf3d-readyplayerme-threejs-boilerplate#3]
When the command ``` npm run build ``` is run and when the div ```     <div id="3d_avatar"></div> ``` is added, nothing seems to work correctly

**Comment by egemenertugrul** [comment]
Hey @Yasha-ops, you should include the .js file output to the `dist` folder after you ran `npm run build` in your HTML.

**Comment by emorling** [comment]
> Hey @Yasha-ops, you should include the .js file output to the `dist` folder after you ran `npm run build` in your HTML.

I can't either get this to work. I am no wadding:
`<div id="3d_avatar"></div>`
To the generated html file in the dist folder.
Is this not the intended process?
